extends Node

const PROMPTS := {
    "SEE_WATCH":"WATCH THE PATTERN", "SEE_SELECT":"SELECT THE CHANGED ONE", "SEE_ROTATION_VISUAL":"ONE SYMBOL IS ROTATED", "SEE_PATTERN_VISUAL":"ONE SYMBOL BREAKS THE PATTERN", "SEE_DUPLICATE_VISUAL":"ONE SYMBOL APPEARS TWICE", "SEE_SPEED":"WATCH THE SPEED", "SEE_SPEED_CHOOSE":"WHICH ONE CHANGED SPEED?", "REMEMBER_MEMORIZE":"MEMORIZE", "REMEMBER_CHOOSE":"CHOOSE THE REMEMBERED TARGET", "REACT_WAIT":"WAIT...", "REACT_WATCH":"WATCH THE SIGNAL", "REACT_NOW":"REACT NOW", "TOO_SLOW":"TOO SLOW", "SWITCH_RULE_ONE":"RULE 1", "SWITCH_RULE_CHANGED":"RULE CHANGED", "SWITCH_CHOOSE":"CHOOSE", "SWITCH_BLUE":"TAP BLUE", "SWITCH_SIGNAL":"WATCH FOR THE SIGNAL", "SWITCH_NO_REPEAT":"DO NOT REPEAT THE PREVIOUS MOVE", "SWITCH_NEW_RULE":"FOLLOW THE NEW RULE", "SWITCH_NEW_SIGNAL":"SWITCH RULE NOW", "SWITCH_REVERSE":"REVERSE THE RULE", "SWITCH_NUMBER":"TARGET NUMBER CHANGED", "SWITCH_SHAPE":"TARGET SHAPE CHANGED", "SWITCH_DIRECTION":"DIRECTION CHANGED", "SWITCH_TIMING":"TIMING RULE CHANGED", "SWITCH_ACTION":"REQUIRED ACTION CHANGED", "TRICK_OBVIOUS":"DO NOT TRUST THE OBVIOUS MOVE", "TRICK_SIZE":"THE SIZE IS A DECOY", "TRICK_FIRST_IS_DECOY":"THE FIRST IMPRESSION IS WRONG", "TRICK_WORD_COLOR":"THE WORD AND COLOR DISAGREE", "TRICK_FORBIDDEN":"THE FORBIDDEN-LOOKING OPTION IS CORRECT", "TRICK_SLOWEST":"THE SLOWEST OPTION IS CORRECT", "TRICK_DECOY":"IGNORE THE DECOY", "TRICK_EXCEPTION":"CHOOSE THE EXCEPTION", "TRICK_LABEL":"IGNORE THE LABEL; FOLLOW THE RULE", "TRICK_LATEST":"FOLLOW THE LATEST RULE", "TRICK_HIDDEN":"THE EXCEPTION IS HIDDEN", "TRICK_READ_RULE":"READ THE RULE, NOT YOUR FIRST IMPRESSION", "MIX_SEE":"SEE", "MIX_NOTICE":"NOTICE THE PATTERN", "MIX_SWITCH":"SWITCH", "MIX_REACT":"REACT", "MIX_CHOOSE_SIGNAL":"WHICH SIGNAL CAME AFTER THE CHANGE?", "UNSUPPORTED_CHALLENGE":"CHALLENGE UNAVAILABLE"
}

func _ready() -> void:
    var english := Translation.new()
    english.set_locale("en")
    for key in PROMPTS:
        english.add_message(key, str(PROMPTS[key]))
    var manager_script = load("res://scripts/core/challenge_manager.gd")
    if manager_script:
        var manager = manager_script.new()
        for challenge in manager.challenges:
            var rule_key := str(challenge.get("rule_key", ""))
            var description := str(challenge.get("description", ""))
            if not rule_key.is_empty() and not description.is_empty():
                english.add_message(rule_key, description.to_upper())
    TranslationServer.add_translation(english)
